src/app/views.py
# views.py
from flask import Blueprint, render_template, request, redirect, flash, url_for
from dotenv import load_dotenv
from flask_login import login_user, current_user, logout_user, login_required
from .models import Users, db, User_has_Mcsrv, Mcsrvs
from .AWS import AWS
import bcrypt
import json
import os
import random
import string

load_dotenv()

views = Blueprint('views', __name__)
aws = AWS(os.environ.get("RCON_PASSWORD"))


@views.route("/")
@login_required
def home():
    owned_srv = db.session.query(
        Mcsrvs.name_mcsrv.label('name'),
        Mcsrvs.id_mcsrv.label('id'),
        User_has_Mcsrv.name_user.label('name_user')
    ).join(
        User_has_Mcsrv, User_has_Mcsrv.id_mcsrv == Mcsrvs.id_mcsrv
    ).join(
        Users, User_has_Mcsrv.name_user == Users.name_user
    ).filter(
        User_has_Mcsrv.id_role == 1,
        Users.name_user == current_user.name_user
    ).all()

    member_srv = db.session.query(
        Mcsrvs.name_mcsrv.label('name'),
        Mcsrvs.id_mcsrv.label('id')
    ).join(
        User_has_Mcsrv, User_has_Mcsrv.id_mcsrv == Mcsrvs.id_mcsrv
    ).filter(
        User_has_Mcsrv.name_user == current_user.name_user,
        User_has_Mcsrv.id_role == 2
    ).all()

    return render_template('home.html', owned_srv=owned_srv, member_srv=member_srv)


@views.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        password = request.form['password']

        if Users.query.filter_by(name_user=username).first():
            flash("This username is already used", "danger")
            return redirect('/register')
        elif Users.query.filter_by(email_user=email).first():
            flash("This email is already used", "danger")
            return redirect('/register')

        # Hash the password using bcrypt
        hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())

        # Create new user
        new_user = Users(name_user=username, email_user=email, hash_user=hashed_password)
        db.session.add(new_user)
        db.session.commit()

        login_user(new_user)

        return redirect('/')

    return render_template('register.html')


@views.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        username = request.form["username"]
        password = request.form["password"]

        user = Users.query.filter_by(name_user=username).first()
        if not user:
            print("no user")
            return render_template('login.html')
        if bcrypt.checkpw(password.encode('utf-8'), user.hash_user.encode('utf-8')):
            login_user(user)
        else:
            print("wrong password")
            return render_template('login.html')
    return render_template('login.html')


@views.route('/logout')
def logout():
    logout_user()
    return redirect('/login')


@views.route('/create_server', methods=["GET", "POST"])
@login_required
def create_server():
    if request.method == 'POST':
        name_srv = request.form['namesrv']

        name = current_user.name_user + '-' + name_srv
        service_name = 'service' + '-' + name_srv
        arn_srv = aws.register_task_definition(name, name_srv)
        service_arn = None
        if arn_srv:
            print("created Task defintion")
            response = aws.invoke_Create_EFS(name_srv)
            if response == 201 or response == 200:
                print("Volume created or it already existed")
                service_arn = aws.create_service(service_name, arn_srv)
                print(service_arn)
            else:
                print("Opfer1")
        else:
            print("Opfer")

        mcsrv = Mcsrvs(arn_taskdef_mcsrv=arn_srv, arn_service_mcsrv=service_arn, name_mcsrv=name_srv)
        db.session.add(mcsrv)
        db.session.commit()

        mcsrv = Mcsrvs.query.filter_by(arn_taskdef_mcsrv=arn_srv).first()
        if mcsrv:
            u_h_m = User_has_Mcsrv(name_user=current_user.name_user, id_mcsrv=mcsrv.id_mcsrv, id_role=1)
            db.session.add(u_h_m)
            db.session.commit()
            return redirect('/')
        else:
            print("something went wrong")

    return render_template('create_server.html')


@views.route('/edit_server/<server_id>', methods=["GET", "POST"])
@login_required
def edit_server(server_id):
    mcsrv = Mcsrvs.query.filter_by(id_mcsrv=server_id).first()
    status, ip, hostname= aws.server_info(mcsrv.arn_service_mcsrv)

    if not ip:
        flash("Server is stopped")
        return redirect('/')

    if request.method == 'POST':
        mcsrv.name_mcsrv = request.form['namesrv']
        mcsrv.whitelist = json.dumps(request.form.getlist('whitelist'))
        db.session.commit()
        return redirect('/')
    whitelist = aws.whitelist_list(ip)

    split_by_colon = whitelist.split(':')
    if len(split_by_colon) == 2:
        usernames_part = split_by_colon[1].strip()
        whitelist = [user.strip() for user in usernames_part.split(',')]
    else:
        whitelist = []
    return render_template('edit_server.html', name_server=mcsrv.name_mcsrv, id_server=server_id, whitelist=whitelist)


@views.route('/server/<server>')
@login_required
def server(server):
    mcsrv = Mcsrvs.query.filter_by(id_mcsrv=server).first()
    status, ip, server_address = aws.server_info(mcsrv.arn_service_mcsrv)
    print(mcsrv.arn_service_mcsrv)
    print(ip)
    return render_template("server_info.html", server=server, status=status, ip_address=ip, server_address=server_address)


@views.route('/server/<server>/stop', methods=["POST"])
@login_required
def stop_server(server):
    mcsrv = Mcsrvs.query.filter_by(id_mcsrv=server).first()
    if aws.stop_server(mcsrv.arn_service_mcsrv, 0):
        print("Stopping")
    else:
        print("not Stopping")

    return redirect('/')


@views.route('/server/<server>/start', methods=["POST"])
@login_required
def start_server(server):
    mcsrv = Mcsrvs.query.filter_by(id_mcsrv=server).first()
    if aws.stop_server(mcsrv.arn_service_mcsrv, 1):
        print("Starting")
    else:
        print("not Starting")

    return redirect('/')


@views.route('/server/<int:server_id>/whitelist/add', methods=['POST'])
def add_to_whitelist(server_id):
    usernames = request.form.get('usernames').split(',')
    server = Mcsrvs.query.get(server_id)
    status, public_ip, server_adress = aws.server_info(server.arn_service_mcsrv)

    if status == "RUNNING" and public_ip:
        print(public_ip, usernames)
        aws.whitelist_add(public_ip, usernames)
        return redirect(url_for('views.edit_server', server_id=server_id))
    else:
        return "Server not running", 400


@views.route('/server/<int:server_id>/whitelist/remove', methods=['POST'])
def remove_from_whitelist(server_id):
    usernames = request.form.get('usernames').split(',')
    server = Mcsrvs.query.get(server_id)
    status, public_ip, server_address = aws.server_info(server.arn_service_mcsrv)

    if status == "RUNNING" and public_ip:
        aws.whitelist_remove(public_ip, usernames)
        return redirect(url_for('views.edit_server', server_id=server_id))
    else:
        return "Server not running", 400


@views.route('/server/<server_id>/backup', methods=['POST'])
def backup(server_id):
    try:
        server_details = Mcsrvs.query.filter_by(id_mcsrv=server_id).first()

        if server_details:
            server_name = server_details.name_mcsrv
            s3_directory_id = ''.join(random.choices(string.ascii_lowercase + string.digits, k=10))

            efs_path = f"/mnt/{server_name}"

            s3_path = f"backups/{s3_directory_id}"

            success = aws.upload_files(efs_path, s3_path)

            if not success:
                print(success)
                return "Failed to upload files to S3", 500

            # Add entry to the database for this backup
            try:
                # Create a new entry in Backups table
                new_backup = Backups(
                    path_s3=s3_path,
                    id_mcsrv=server_id  # Assuming id_mcsrv is the foreign key reference
                )

                db.session.add(new_backup)
                db.session.commit()

                return f"Backup for server ID {server_id} ({server_name}) completed and saved in S3 at {s3_path}", 200

            except Exception as e:
                db.session.rollback()
                return f"Failed to create backup entry in database: {str(e)}", 500

        else:
            return f"Server with ID {server_id} not found in database", 404

    except Exception as e:
        return f"Error fetching server details: {str(e)}", 500
@views.route('/server/<server>/restore_backup')
def restore_backup(server):
    return "nice"

src/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Flask App{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <!-- Sidebar -->
            <nav id="sidebar" class="col-md-2 col-lg-1 d-md-block bg-dark sidebar">
                <div class="sidebar-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link text-light" href="/">
                                <div class="sidebar-icon">&#9733;</div>
                                Dashboard
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="#">
                                <div class="sidebar-icon">&#128178;</div>
                                Orders
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="#">
                                <div class="sidebar-icon">&#128203;</div>
                                Products
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="#">
                                <div class="sidebar-icon">&#128100;</div>
                                Customers
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="sidebar-footer">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link text-light" href="/logout">
                                <div class="sidebar-icon">&#128682;</div>
                                Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
            <!-- Content -->
            <main role="main" class="col-md-10 ml-sm-auto col-lg-11 px-md-4">
                    {% with messages = get_flashed_messages() %}
    {% if messages %}
        <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
        </ul>
    {% endif %}
    {% endwith %}
                <h1 class="underlined-title mt-4">{% block p_title %}Page Title{% endblock %}</h1>
                {% block content %}
                {% endblock %}
            </main>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

src/app/templates/create_server.html
<!-- create_server.html -->
{% extends "base.html" %}
{% block title %}Create Card{% endblock %}
{% block p_title %}Create New Card{% endblock %}
{% block content %}

<div class="container mt-5">
    <form method="post" action="{{ url_for('views.create_server') }}">
        <div class="form-group">
            <label for="cardTitle">Card Title</label>
            <input type="text" class="form-control" id="namesrv" name="namesrv" placeholder="Enter Server Name" required>
        </div>
        <div class="form-group">
            <label for="cardText">Card Text</label>
            <textarea class="form-control" id="cardText" name="cardText" rows="3" placeholder="Enter card text" ></textarea>
        </div>
        <div class="form-group">
            <label for="cardImage">Card Image URL</label>
            <input type="url" class="form-control" id="cardImage" name="cardImage" placeholder="Enter image URL" >
        </div>
        <button type="submit" class="btn btn-primary">Create Card</button>
    </form>
</div>

{% endblock %}

src/app/templates/edit_server.html
{% extends "base.html" %}
{% block title %}Edit Server{% endblock %}
{% block p_title %}Edit Server{% endblock %}
{% block content %}

<div class="container mt-5">
    <form method="post" action="{{ url_for('views.edit_server', server_id=id_server) }}">
        <div class="form-group">
            <label for="cardTitle">Card Title</label>
            <input type="text" class="form-control" id="namesrv" name="namesrv" value="{{ name_server }}" required>
        </div>
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>

    <div class="mt-5">
        <h3>Whitelisted Users</h3>
        <ul class="list-group">
            {% for user in whitelist %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ user }}
                <form method="post" action="{{ url_for('views.remove_from_whitelist', server_id=id_server) }}">
                    <input type="hidden" name="usernames" value="{{ user }}">
                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                </form>
            </li>
            {% endfor %}
        </ul>
    </div>
        <form method="post" action="{{ url_for('views.add_to_whitelist', server_id=id_server) }}" class="mt-3">
        <div class="form-group">
            <label for="usernames">Add Whitelist Users (comma separated)</label>
            <input type="text" class="form-control" id="usernames" name="usernames" placeholder="Enter usernames">
        </div>
        <button type="submit" class="btn btn-success">Add to Whitelist</button>
    </form>
</div>

{% endblock %}

src/app/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block p_title %}Pixelcube{% endblock %}
{% block content %}

<h2 class="underlined-title">Owned Minecraft Servers</h2>
<div class="card-container">
    {% for srv in owned_srv %}
      <div class="card" style="width: 18rem;">
        <img src="https://img1.exportersindia.com/product_images/bc-small/2019/12/4623921/aluminium-composite-panel-1575450560-5194321.jpeg" class="card-img-top" alt="..." style="filter: hue-rotate({{ loop.index * 30 }}deg);">
        <div class="card-body">
          <h5 class="card-title">{{srv[0]}}</h5>
          <p class="card-text"><b>owner:</b> {{srv[2]}}</p>
          <a href="/server/{{ srv[1] }}" class="btn btn-primary" style="filter: hue-rotate({{ loop.index * 30 }}deg);">Go to VM</a>
          <a href="/edit_server/{{ srv[1] }}" class="btn btn-primary" style="filter: hue-rotate({{ loop.index * 30 }}deg);">Edit Course</a>
        </div>
      </div>
    {% endfor %}
</div>


<a href="/create_server" class="btn btn-primary create-card-btn">Create Server</a>

{% endblock %}

src/app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body class="bg-light">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 rounded shadow-sm">
                <h1 class="underlined-title mt-4">Login</h1>
                <form method="POST" action="/login">
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input type="text" class="form-control" id="username" name="username" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" id="password" name="password" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Login</button>
                </form>
                <p class="mt-3">Don't have an account? <a href="/register">Register here</a>.</p>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

src/app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body class="bg-light">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 rounded shadow-sm">
                <h1 class="underlined-title mt-4">Register</h1>
                <form method="POST" action="/register">
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input type="text" class="form-control" id="username" name="username" required>
                    </div>
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" id="password" name="password" required>
                    </div>
                    <div class="form-group">
                        <label for="confirm_password">Confirm Password</label>
                        <input type="password" class="form-control" id="confirm_password" name="confirm_password" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Register</button>
                </form>
                <p class="mt-3">Already have an account? <a href="/login">Login here</a>.</p>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

src/app/templates/server_info.html
{% extends "base.html" %}
{% block title %} Server - {{ name }} {% endblock %}
{% block content %}
<div class="vm_desc">
    <div class="row">
        <div class="col-md-6">
            <b>Status:</b>
            <p>{{ status }}</p>
            <br>
            <b>Name:</b>
            <p>{{ name }}</p>
            <br>
        </div>
        <div class="col-md-6">
            <b>Password:</b>
            <p>-</p>
            <br>
            <b>Description:</b>
            <p>{{ description }}</p>
            <br>
        </div>
    </div>

    <b>Hardware</b>
    <hr color="black">

    <div class="row">
        <div class="col-md-6">
            <b>CPU:</b>
            <p>{{ cpu }}</p>
            <br>
            <b>Storage:</b>
            <p>{{ storage }}</p>
            <br>
        </div>
        <div class="col-md-6">
            <b>RAM:</b>
            <p>{{ ram }}</p>
            <br>
            <b>OS:</b>
            <p>{{ operatingsystem }}</p>
            <br>
        </div>
    </div>

    <b>Connectivity</b>
    <hr color="black">

    <div class="row">
        <div class="col-md-6">
            <b>IP:</b>
            <p>{{ ip_address }}</p>
        </div>
        <div class="col-md-6">
            <b>Hostname:</b>
            <p>{{ server_address }}</p>
        </div>
    </div>
</div>

<div class="vm_actions mt-4">
    <h2>VM Actions</h2>
    <form action="{{ url_for('views.start_server', server=server) }}" method="post">
        <button class="btn btn-primary action_btn" id="start_vm_btn" type="submit">Start</button>
    </form>
    <form action="{{ url_for('views.stop_server', server=server) }}" method="post">
        <button class="btn btn-danger action_btn" id="stop_vm_btn" type="submit">Shutdown</button>
    </form>
    <form action="{{ url_for('views.backup', server_id=server) }}" method="post">
        <label for="backup_name">Backup:</label>
        <input type="text" id="backup_name" name="backup_name" placeholder="Backup name">
        <button class="btn btn-warning action_btn" id="reboot_to_backup_btn" type="submit">Backup</button>
    </form>
    <form action="{{ url_for('views.restore_backup', server=server) }}" method="post">
        <label for="backup_select">Restore Backup:</label>
        <select id="backup_select" name="backup_select">
            {% for backup in backups %}
            <option value="{{ backup.id }}">{{ backup.name }}</option>
            {% endfor %}
        </select>
        <button class="btn btn-info action_btn" id="restore_backup_btn" type="submit">Restore</button>
    </form>
</div>

<style>
    .vm_desc {
        margin-top: 20px;
    }
    .vm_desc b {
        font-size: 1.2em;
    }
    .vm_desc p {
        font-size: 1em;
    }
    .vm_actions {
        margin-top: 30px;
    }
    .action_btn {
        width: 150px;
        margin: 5px;
    }
</style>
{% endblock %}